version: "3.9"
services:
  etcd:
    build:
      context: etcd_custom
    image: etcd_custom 
    ports:
      - "2379:2379"
    environment:
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2380"
      ALLOW_NONE_AUTHENTICATION: "yes"
  benchmark:
    image: etcd-benchmark 
    build:
      context: .
      dockerfile: ./Dockerfile.bench
    ports:
      - "8080:8080"
    environment:
      BENCHMARK_EXEC: /bin/benchmark-client
