version: "3.9"
services:
  etcd:
    image: bitnami/etcd:3.3.27-debian-10-r63
    ports:
      - "2379:2379"
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
  benchmark:
    image: etcd-benchmark 
    build:
      context: .
      dockerfile: ./Dockerfile.bench
    ports:
      - "8080:8080"
    environment:
      BENCHMARK_EXEC: /bin/benchmark-client